---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "jenkins-master"
  labels:
    app: jenkins-master
    version: "1.0.0"
    group: "jenkins"
  namespace: "jenkins"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jenkins-master"
      version: "1.0.0"
      group: "jenkins"
  template:
    metadata:
      labels:
        app: jenkins-master
        version: "1.0.0"
        group: "jenkins"
    spec:
      serviceAccount: "jenkins-admin"
      containers:
        - name: "jenkins-master"
          image: "richardx/jenkins-master:1.0.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: "/var/jenkins_home"
            - name: jenkins-configuration-as-code
              mountPath: "/var/jenkins_config"
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
      volumes:
        - name: jenkins-home
          #          emptyDir: {}
          persistentVolumeClaim:
            claimName: "jenkins-pvc"
            readOnly: false
        - name: jenkins-configuration-as-code
          configMap:
            name: jenkins-configuration-as-code
