---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jenkins-master
    version: "latest"
    group: "jenkins"
  name: jenkins-admin
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
  labels:
    app: jenkins-master
    version: "latest"
    group: "jenkins"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins

