folder('Inital-JCasC')
pipelineJob('Inital-JCasC/job-dsl-plugin') {
  definition {
    cpsScm {
      scm {
        git {
          remote {
            url('https://github.com/xiaojias/jenkins-casc.git')
          }
          branch('*/wip')
        }
      }
      lightweight()
    }
  }
}

