folder('Inital-JCasC')
pipelineJob('Inital-JCasC/job-dsl-plugin') {
  definition {
    cpsScm {
      scm {
        git {
          remote {
            url('git@github.com:xiaojias/devops-cicd.git')
            credentials('credential-github-xiaojias')
          }
          branch('*/wip')
          // GitContext.script('app01.Jenkinsfile')
        }
      }
      lightweight()
    }
  }
}

