apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-slave
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  local:
    path: /pv-slave
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ecs-00
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
