apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: jenkins
spec:
  hostname: busybox1
  subdomain: xiaojias
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: jenkins
spec:
  hostname: busybox2
  subdomain: xiaojias
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
