apiVersion: v1
kind: Pod
metadata:
  name: busybox-sample
  namespace: jenkins
spec:
  hostname: busybox-sample
  subdomain: xiaojias
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

---
