# Define a simple Pod template
apiVersion: v1
kind: Pod
metadata:
  name: pod-sample
spec:
  containers:
  - name: container0
    image: busybox
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
