# Create jobs from every branch for a project (github)

jobs:
  - script: >
      multibranchPipelineJob('Project-test-cicd') {
        branchSources {
          github {
            // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
            id('12312313') // IMPORTANT: use a constant and unique identifier
            scanCredentialsId('credential-github-xiaojias')
            repoOwner('xiaojias')
            repository('jenkins-jcasc')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(1)
          }
        }
        triggers {
          periodic(5)
        }
      }
