jobs:
  - script: >
      folder('Initial-Jobs')
  - script: >
      pipelineJob('Initial-Jobs/default-agent') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }

  - script: >
      pipelineJob('Initial-Jobs/job-dsl-plugin-app01') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@github.com:xiaojias/devops-cicd.git')
                  credentials('credential-github-xiaojias')
                }
                branch('*/wip')
                scriptPath('app01.Jenkinsfile')
              }
            }
            lightweight()
          }
        }
      }
